<?php

namespace Automattic\WooCommerce\Admin\API\AI;

/**
 * Store Title controller
 *
 * @internal
 */
class StoreTitle extends \Automattic\WooCommerce\Admin\API\AI\AIEndpoint
{
    /**
     * The store title option name.
     *
     * @var string
     */
    const STORE_TITLE_OPTION_NAME = 'blogname';
    /**
     * The AI generated store title option name.
     *
     * @var string
     */
    const AI_STORE_TITLE_OPTION_NAME = 'ai_generated_site_title';
    /**
     * The default store title.
     *
     * @var string
     */
    const DEFAULT_TITLE = 'Site Title';
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'store-title';
    /**
     * Register routes.
     */
    public function register_routes()
    {
    }
    /**
     * Update the store title powered by AI.
     *
     * @param  WP_REST_Request $request Request object.
     *
     * @return WP_Error|WP_REST_Response
     */
    public function update_store_title($request)
    {
    }
    /**
     * Generate the store title powered by AI.
     *
     * @param string $business_description The business description for a given store.
     *
     * @return string|WP_Error|WP_REST_Response The store title generated by AI.
     */
    private function generate_ai_title($business_description)
    {
    }
    /**
     * Get the Business Description response.
     *
     * @return array
     */
    public function get_schema()
    {
    }
}