<?php


/**
 * Template loader class.
 */
class WC_Template_Loader
{
    /**
     * Store the shop page ID.
     *
     * @var integer
     */
    private static $shop_page_id = 0;
    /**
     * Store whether we're processing a product inside the_content filter.
     *
     * @var boolean
     */
    private static $in_content_filter = \false;
    /**
     * Is WooCommerce support defined?
     *
     * @var boolean
     */
    private static $theme_support = \false;
    /**
     * Hook in methods.
     */
    public static function init()
    {
    }
    /**
     * Load a template.
     *
     * Handles template usage so that we can use our own templates instead of the theme's.
     *
     * Templates are in the 'templates' folder. WooCommerce looks for theme
     * overrides in /theme/woocommerce/ by default.
     *
     * For beginners, it also looks for a woocommerce.php template first. If the user adds
     * this to the theme (containing a woocommerce() inside) this will be used for all
     * WooCommerce templates.
     *
     * @param string $template Template to load.
     * @return string
     */
    public static function template_loader($template)
    {
    }
    /**
     * Checks whether a block template with that name exists.
     *
     * @since  5.5.0
     * @param string $template_name Template to check.
     * @return boolean
     */
    private static function has_block_template($template_name)
    {
    }
    /**
     * Get the default filename for a template except if a block template with
     * the same name exists.
     *
     * @since  3.0.0
     * @since  5.5.0 If a block template with the same name exists, return an
     * empty string.
     * @return string
     */
    private static function get_template_loader_default_file()
    {
    }
    /**
     * Get an array of filenames to search for a given template.
     *
     * @since  3.0.0
     * @param  string $default_file The default file name.
     * @return string[]
     */
    private static function get_template_loader_files($default_file)
    {
    }
    /**
     * Load comments template.
     *
     * @param string $template template to load.
     * @return string
     */
    public static function comments_template_loader($template)
    {
    }
    /**
     * Unsupported theme compatibility methods.
     */
    /**
     * Hook in methods to enhance the unsupported theme experience on pages.
     *
     * @since 3.3.0
     */
    public static function unsupported_theme_init()
    {
    }
    /**
     * Hook in methods to enhance the unsupported theme experience on the Shop page.
     *
     * @since 3.3.0
     */
    private static function unsupported_theme_shop_page_init()
    {
    }
    /**
     * Hook in methods to enhance the unsupported theme experience on Product pages.
     *
     * @since 3.3.0
     */
    private static function unsupported_theme_product_page_init()
    {
    }
    /**
     * Add theme support for Product page gallery.
     *
     * @since x.x.x
     */
    private static function add_support_for_product_page_gallery()
    {
    }
    /**
     * Enhance the unsupported theme experience on Product Category and Attribute pages by rendering
     * those pages using the single template and shortcode-based content. To do this we make a dummy
     * post and set a shortcode as the post content. This approach is adapted from bbPress.
     *
     * @since 3.3.0
     */
    private static function unsupported_theme_tax_archive_init()
    {
    }
    /**
     * Add layered nav args to WP_Query args generated by the 'products' shortcode.
     *
     * @since 3.3.4
     * @param array $query WP_Query args.
     * @return array
     */
    public static function unsupported_archive_layered_nav_compatibility($query)
    {
    }
    /**
     * Force the loading of one of the single templates instead of whatever template was about to be loaded.
     *
     * @since 3.3.0
     * @param string $template Path to template.
     * @return string
     */
    public static function force_single_template_filter($template)
    {
    }
    /**
     * Get information about the current shop page view.
     *
     * @since 3.3.0
     * @return array
     */
    private static function get_current_shop_view_args()
    {
    }
    /**
     * Filter the title and insert WooCommerce content on the shop page.
     *
     * For non-WC themes, this will setup the main shop page to be shortcode based to improve default appearance.
     *
     * @since 3.3.0
     * @param string $title Existing title.
     * @param int    $id ID of the post being filtered.
     * @return string
     */
    public static function unsupported_theme_title_filter($title, $id)
    {
    }
    /**
     * Filter the content and insert WooCommerce content on the shop page.
     *
     * For non-WC themes, this will setup the main shop page to be shortcode based to improve default appearance.
     *
     * @since 3.3.0
     * @param string $content Existing post content.
     * @return string
     */
    public static function unsupported_theme_shop_content_filter($content)
    {
    }
    /**
     * Filter the content and insert WooCommerce content on the shop page.
     *
     * For non-WC themes, this will setup the main shop page to be shortcode based to improve default appearance.
     *
     * @since 3.3.0
     * @param string $content Existing post content.
     * @return string
     */
    public static function unsupported_theme_product_content_filter($content)
    {
    }
    /**
     * Suppress the comments number on the Shop page for unsupported themes since there is no commenting on the Shop page.
     *
     * @since 3.4.5
     * @param string $comments_number The comments number text.
     * @return string
     */
    public static function unsupported_theme_comments_number_filter($comments_number)
    {
    }
    /**
     * Are we filtering content for unsupported themes?
     *
     * @since 3.3.2
     * @return bool
     */
    public static function in_content_filter()
    {
    }
    /**
     * Prevent the main featured image on product pages because there will be another featured image
     * in the gallery.
     *
     * @since 3.3.0
     * @param string $html Img element HTML.
     * @return string
     */
    public static function unsupported_theme_single_featured_image_filter($html)
    {
    }
    /**
     * Remove the Review tab and just use the regular comment form.
     *
     * @param array $tabs Tab info.
     * @return array
     */
    public static function unsupported_theme_remove_review_tab($tabs)
    {
    }
}