<?php

namespace Automattic\WooCommerce\StoreApi\Routes\V1\AI;

/**
 * Patterns class.
 *
 * @internal
 */
class Patterns extends \Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute
{
    /**
     * The route identifier.
     *
     * @var string
     */
    const IDENTIFIER = 'ai/patterns';
    /**
     * The schema item identifier.
     *
     * @var string
     */
    const SCHEMA_TYPE = 'ai/patterns';
    /**
     * Get the path of this REST route.
     *
     * @return string
     */
    public function get_path()
    {
    }
    /**
     * Get method arguments for this REST route.
     *
     * @return array An array of endpoints.
     */
    public function get_args()
    {
    }
    /**
     * Update patterns with the content and images powered by AI.
     *
     * @param  \WP_REST_Request $request Request object.
     *
     * @return WP_Error|\WP_HTTP_Response|\WP_REST_Response
     */
    protected function get_route_post_response(\WP_REST_Request $request)
    {
    }
    /**
     * Remove patterns generated by AI.
     *
     * @param  \WP_REST_Request $request Request object.
     *
     * @return bool|string|WP_Error|\WP_REST_Response
     */
    protected function get_route_delete_response(\WP_REST_Request $request)
    {
    }
}