<?php

namespace Automattic\WooCommerce\Admin;

/**
 * Class WCAdminHelper
 */
class WCAdminHelper
{
    /**
     * WC Admin timestamp option name.
     */
    const WC_ADMIN_TIMESTAMP_OPTION = 'woocommerce_admin_install_timestamp';
    const WC_ADMIN_STORE_AGE_RANGES = array('week-1' => array('start' => 0, 'end' => WEEK_IN_SECONDS), 'week-1-4' => array('start' => WEEK_IN_SECONDS, 'end' => WEEK_IN_SECONDS * 4), 'month-1-3' => array('start' => MONTH_IN_SECONDS, 'end' => MONTH_IN_SECONDS * 3), 'month-3-6' => array('start' => MONTH_IN_SECONDS * 3, 'end' => MONTH_IN_SECONDS * 6), 'month-6+' => array('start' => MONTH_IN_SECONDS * 6));
    /**
     * Get the number of seconds that the store has been active.
     *
     * @return number Number of seconds.
     */
    public static function get_wcadmin_active_for_in_seconds()
    {
    }
    /**
     * Test how long WooCommerce Admin has been active.
     *
     * @param int $seconds Time in seconds to check.
     * @return bool Whether or not WooCommerce admin has been active for $seconds.
     */
    public static function is_wc_admin_active_for($seconds)
    {
    }
    /**
     * Test if WooCommerce Admin has been active within a pre-defined range.
     *
     * @param string $range range available in WC_ADMIN_STORE_AGE_RANGES.
     * @param int    $custom_start custom start in range.
     * @throws \InvalidArgumentException Throws exception when invalid $range is passed in.
     * @return bool Whether or not WooCommerce admin has been active within the range.
     */
    public static function is_wc_admin_active_in_date_range($range, $custom_start = null)
    {
    }
    /**
     * Test if the site is fresh. A fresh site must meet the following requirements.
     *
     * - The current user was registered less than 1 month ago.
     * - fresh_site option must be 1
     *
     * @return bool
     */
    public static function is_site_fresh()
    {
    }
    /**
     * Test if a URL is a store page. This function ignores the domain and protocol of the URL and only checks the path and query string.
     *
     * Store pages are defined as:
     *
     * - Shop
     * - Cart
     * - Checkout
     * - Privacy Policy
     * - Terms and Conditions
     *
     * Additionally, the following autogenerated pages should be included:
     * - Product pages
     * - Product Category pages
     * - Product Tag pages
     *
     * @param string $url URL to check. If not provided, the current URL will be used.
     * @return bool Whether or not the URL is a store page.
     */
    public static function is_store_page($url = '')
    {
    }
    /**
     * Get normalized URL path.
     * 1. Only keep the path and query string (if any).
     * 2. Remove wp home path from the URL path if WP is installed in a subdirectory.
     * 3. Remove leading and trailing slashes.
     *
     * For example:
     *
     * - https://example.com/wordpress/shop/uncategorized/test/?add-to-cart=123 => shop/uncategorized/test/?add-to-cart=123
     *
     * @param string $url URL to normalize.
     */
    private static function get_normalized_url_path($url)
    {
    }
}